 DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(
  ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  BIRTHDAY DATE,
  AGE INT);
INSERT INTO TEST VALUES(1, 'Hello', '2001-01-02', 18);
INSERT INTO TEST VALUES(2, 'World', '2000-02-01', 19);
SELECT * FROM TEST ORDER BY ID;
UPDATE TEST SET NAME='Hi' WHERE ID=1;